server:
  port: 4329
spring:
  application:
    name: freshwater-boot-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/freshwater?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 20
      initialSize: 1
      maxWait: -1
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      removeAbandonedTimeout: 180
      logAbandoned: true
      maxPoolPreparedStatementPerConnectionSize: 20
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

redis:
  model: single
  address: 127.0.0.1:6379
  database: 9
  password:

mybatis-plus:
  mapper-locations: classpath*:**/mapper/**/*Mapper.xml
  global-config:
    db-config:
      update-strategy: ignored

logging:
  level:
    org.freshwater.boot: DEBUG
  file:
    path: E:/crawler/logs
    name: freshwater-boot-web

freshwater:
  jwt: # JWT
    header: Authorization
    expire: 604800
    secret: f4e2e52034348f86b67cde581c0f9eb5
  file: # 文件上传下载
    root: D:/Download/
    white: txt,png,pdf,jpg,xlsx
    max: 10